#define SET 0
#define PLUS 1
#define LESS 2
#define FACT 3
#define SUBS 4
#define OPENBRACE 5
#define CLOSEBRACE 6
#define OPENPAR 7
#define CLOSEPAR 8
#define EQUAL 9
#define SEMICOLON 10
#define NUMBER 15
#define ID 16